### ISSUE TITLE
use prun content overflowed

### ISSUE THREAD

**Issue by geekris1** [Simon-He95/pi#43] opened 2023-10-23 09:25 UTC
<img width="250" alt="image" src="https://github.com/Simon-He95/pi/assets/35247521/810984b0-4d0f-4bcc-9c94-9e7b6f6e39f3">

**Comment by Simon-He95** [comment] 2023-10-26 09:26
I can't reproduce this problem, maybe because of gum configuration related issues, I will temporarily close this issue

**Closed by Simon-He95** 2023-10-26 09:26 UTC
